spring.application.name=hello_world_api

server.port=8080

HELLO=http://hello-api:8081
WORLD=http://world-api:8082

logging.level.org.springframework=DEBUG
logging.level.com.example.hello_world_api=DEBUG