spring.application.name=db_service

server.port=8083

spring.r2dbc.url=r2dbc:postgresql://postgres:5432/db_service_pg
spring.r2dbc.username=${DB_USER}
spring.r2dbc.password=${DB_PASSWORD}

spring.sql.init.mode=always
